### ISSUE TITLE
config.serialize() should return Prompt[] instead of Union Type

### ISSUE THREAD

**Issue by rholinshead** [lastmile-ai/aiconfig#476]
Currently, config.serialize returns  a Promise of `Prompt | Prompt[]`, which results in the caller having to do type checking to use the result. Instead, it should always just resolve to Prompt[]. The python side is already doing that

**Comment by saqadri** [comment]
Agreed -- same with `config.run` to return `Output[]` instead

**Comment by rossdanlm** [comment]
The python version of this is fixed in https://github.com/lastmile-ai/aiconfig/pull/632

Working on ts version for this now: https://github.com/lastmile-ai/aiconfig/pull/658

We can close this for the more generalized "all return types should be lists instead of single objects" issue in https://github.com/lastmile-ai/aiconfig/issues/645
